/* Questions and repo analysis shared by the static-SPA stacks (Angular, React): the nginx
   setup being replaced, security headers, the port and where the Go server source goes. */
import * as fs from "fs";
import * as path from "path";
import { Plan, exists, isDir, readText, rel, validPort, walkFiles } from "../../../core/files";
import { Prompter } from "../../../core/prompt";
import { fail, info, line, s, section, warn } from "../../../core/ui";
import { GO_MOD, MAIN_GO } from "./go-server";
import { DEFAULT_HEADERS, RuntimeConfig, renderGeneratedGo } from "./templates";

export * from "./templates";
export { GO_MOD, MAIN_GO } from "./go-server";

export interface NginxScan {
  files: string[];
  headers: [string, string][];
  dynamic: [string, string][];
  proxies: string[];
  listen: string | null;
  /** Directives the static server does not reproduce, as "file: uses 'x'". */
  other: string[];
  /** `try_files ... /index.html`: the SPA fallback the server already provides. */
  spaFallback: boolean;
}

export function scanNginx(repo: string): NginxScan {
  const files = [...walkFiles(repo, (f) => f.endsWith(".conf") && (f.toLowerCase().includes("nginx") || path.basename(f) === "default.conf"))];
  const r: NginxScan = { files, headers: [], dynamic: [], proxies: [], listen: null, other: [], spaFallback: false };
  for (const f of files) {
    const t = readText(f).replace(/#[^\n]*/g, "");
    for (const m of t.matchAll(/\badd_header\s+([\w-]+)\s+("[^"]*"|'[^']*'|[^\s;]+)/g)) {
      let v = m[2];
      if (v.length >= 2 && v[0] === v[v.length - 1] && `"'`.includes(v[0])) v = v.slice(1, -1);
      if (["cache-control", "expires", "pragma"].includes(m[1].toLowerCase())) continue;
      (v.includes("$") ? r.dynamic : r.headers).push([m[1], v]);
    }
    for (const m of t.matchAll(/\bproxy_pass\s+[^;]+;/g)) r.proxies.push(`${path.basename(f)}: ${m[0].trim()}`);
    const l = /\blisten\s+(?:[\d.]+:)?(\d+)/.exec(t);
    if (l && !r.listen) r.listen = l[1];
    if (/\btry_files\s[^;]*\/index\.html\b/.test(t)) r.spaFallback = true;
    for (const kw of ["rewrite", "auth_basic", "auth_request", "limit_req", "sub_filter", "ssl_certificate", "return"])
      if (new RegExp(`(?:^|[;{}\\s])${kw}\\s`).test(t)) r.other.push(`${path.basename(f)}: uses '${kw}'`);
  }
  return r;
}

function previousHeaders(repo: string): [[string, string][], string | null] {
  for (const d of walkFiles(repo, (f) => path.basename(f) === "zz_generated_config.go")) {
    const text = readText(d);
    const m = /var securityHeaders = \[\]\[2\]string\{([\s\S]*?)\n\}/.exec(text);
    if (/generated by distroless-setup/i.test(text) && m) {
      const pairs = [...m[1].matchAll(/\{("(?:[^"\\]|\\.)*"),\s*("(?:[^"\\]|\\.)*")\}/g)].map((x) => [JSON.parse(x[1]), JSON.parse(x[2])] as [string, string]);
      return [pairs, d];
    }
  }
  return [[], null];
}

/** Headers for every response: the defaults, a previous run's choice, then nginx's add_header values. */
export async function gatherHeaders(repo: string, P: Prompter, nginx: NginxScan): Promise<[string, string][]> {
  section("Security headers");
  let headers = new Map(DEFAULT_HEADERS);
  const [prev, gen] = previousHeaders(repo);
  if (prev.length) { info(`using headers from the previous run (${rel(repo, gen!)})`); headers = new Map(prev); }
  for (const [n, v] of nginx.headers) headers.set(n, v);
  for (const [n, v] of nginx.dynamic) warn(`header '${n}: ${v}' uses nginx variables and can't be ported; add it manually if needed`);
  for (;;) {
    for (const [n, v] of headers) line(`     ${n}: ${v}`);
    if (await P.confirm("Send these headers on every response?", true)) return [...headers];
    const next = new Map<string, string>();
    for (const l of await P.lines("Enter headers as 'Name: value'")) {
      const i = l.indexOf(":");
      if (i > 0 && /^[A-Za-z0-9-]+$/.test(l.slice(0, i).trim())) next.set(l.slice(0, i).trim(), l.slice(i + 1).trim());
      else line(`    ${s("ignored invalid line: " + l, "red")}`);
    }
    headers = next;
  }
}

/** Container port, defaulting to the previous (non-privileged) EXPOSE or nginx listen port. */
export async function askPort(P: Prompter, previous: (string | null | undefined)[]): Promise<string> {
  const prev = previous.filter((p): p is string => Boolean(p));
  const portDef = prev.find((p) => !validPort(p)) ?? "8080";
  const priv = prev.find((p) => validPort(p));
  if (priv) info(`previous port ${priv} is privileged; non-root needs >=1024, defaulting to ${portDef}`);
  return P.ask("Container port", portDef, validPort);
}

/** Folder for the Go server source; never silently writes into a folder the tool didn't create. */
export async function askServerDir(repo: string, P: Prompter): Promise<string> {
  section("Server source location");
  let serverDef = "server";
  if (exists(path.join(repo, "server")) && !exists(path.join(repo, "server/zz_generated_config.go"))) {
    warn("a 'server/' directory already exists and wasn't created by this tool");
    serverDef = "distroless-server";
  }
  const serverDir = await P.ask("Directory for the Go server source", serverDef, (v) => (/^[A-Za-z0-9._-]+$/.test(v) ? null : "use a simple folder name"));
  const sd = path.join(repo, serverDir);
  if (isDir(sd) && !exists(path.join(sd, "zz_generated_config.go")) && fs.readdirSync(sd).length)
    if (!(await P.confirm(`'${serverDir}/' is not empty. Write files into it anyway?`, false))) fail("aborted: choose a different server directory");
  return serverDir;
}

/** Plans the three Go server files and returns their repo-relative paths (the build needs them). */
export function planServer(plan: Plan, repo: string, serverDir: string, rc: RuntimeConfig, headers: [string, string][]): string[] {
  const sd = path.join(repo, serverDir);
  plan.write(path.join(sd, "main.go"), MAIN_GO, "static file server");
  plan.write(path.join(sd, "go.mod"), GO_MOD, "Go module");
  plan.write(path.join(sd, "zz_generated_config.go"), renderGeneratedGo(rc, headers), "config fields + headers");
  return ["main.go", "go.mod", "zz_generated_config.go"].map((f) => `${serverDir}/${f}`);
}
