/* Generated files shared by the static-SPA stacks: the Go server's config and the Dockerfile
   stages that compile the server and assemble the distroless/static runtime. */

export const RUNTIME_IMAGE = "gcr.io/distroless/static-debian13:nonroot";
export const GO_IMAGE = "golang:1-alpine";

export const DEFAULT_HEADERS: [string, string][] = [
  ["X-Frame-Options", "SAMEORIGIN"],
  ["X-Content-Type-Options", "nosniff"],
  ["X-XSS-Protection", "1; mode=block"],
  ["Referrer-Policy", "strict-origin-when-cross-origin"],
];

/** Config JSON the server can render from env vars. Disabled: the server only serves files. */
export interface RuntimeConfig {
  enabled: boolean;
  url: string;
  fields: [key: string, env: string, raw: boolean][];
  override: string | null;
}

export const NO_RUNTIME_CONFIG: RuntimeConfig = { enabled: false, url: "", fields: [], override: null };

export function renderGeneratedGo(rc: RuntimeConfig, headers: [string, string][]): string {
  const q = (v: string) => JSON.stringify(v).replace(/[\u007f-￿]/g, (c) => "\\u" + c.charCodeAt(0).toString(16).padStart(4, "0"));
  return [
    `// Code generated by distroless-setup. DO NOT EDIT.`,
    "// Re-run distroless-setup to change these values.",
    "",
    "package main",
    "",
    `const configURLPath = ${q(rc.url)}`,
    "",
    "// configFields maps config.json keys to environment variables (USE_RUNTIME_CONFIG=true).",
    "var configFields = []configField{",
    ...(rc.enabled ? rc.fields.map(([k, e, raw]) => `\t{Key: ${q(k)}, Env: ${q(e)}, Raw: ${raw}},`) : []),
    "}",
    "",
    "var securityHeaders = [][2]string{",
    ...headers.map(([n, v]) => `\t{${q(n)}, ${q(v)}},`),
    "}",
    "",
  ].join("\n");
}

/**
 * Stage 2 (compile the Go server) and stage 3 (the distroless runtime) of a static-SPA
 * Dockerfile. The runtime gets the server binary and the build output, nothing else.
 */
export function renderServeStages(o: { goImage: string; serverDir: string; image: string; out: string; port: string }): string[] {
  return [
    "# ---- Stage 2: build the static file server ----",
    `FROM ${o.goImage} AS server-build`,
    "WORKDIR /src",
    `COPY ${o.serverDir}/ ./`,
    "# Static binary (no libc). The check fails the build if cgo ever sneaks back in.",
    'RUN CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags="-s -w" -o /out/server . \\',
    " && go version -m /out/server | grep -q 'CGO_ENABLED=0'",
    "", "",
    "# ---- Stage 3: runtime (distroless: no shell, no package manager, no libc) ----",
    `FROM ${o.image} AS serve`,
    "WORKDIR /app",
    "# Group 0 ownership keeps files readable under OpenShift's arbitrary UIDs.",
    "COPY --from=server-build --chown=65532:0 /out/server /app/server",
    `COPY --from=build --chown=65532:0 /app/${o.out} /app/www`,
    "",
    `ENV PORT=${o.port} \\`,
    "    STATIC_DIR=/app/www",
    "",
    "USER 65532:0",
    `EXPOSE ${o.port}`,
    "",
    "HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \\",
    '  CMD ["/app/server", "-healthcheck"]',
    "",
    'ENTRYPOINT ["/app/server"]',
    "",
  ];
}
