/* Go static file server source (served on distroless/static). Kept verbatim; repo-specific
   values are generated separately into zz_generated_config.go. */
export const MAIN_GO = String.raw`// Static file server for an Angular SPA on a distroless image.
// Generated by distroless-setup. Repo-specific values live in zz_generated_config.go.
//
// Behaviour: immutable caching for hashed assets (404 when missing), SPA fallback
// to index.html with no-cache, gzip pre-compressed at startup, security headers on
// every response, config JSON rendered in memory from env vars (unset vars keep
// the build-time value), /healthz, and
// graceful shutdown. Nothing is written to disk, so readOnlyRootFilesystem and
// OpenShift arbitrary UIDs work.
package main

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io/fs"
	"log"
	"mime"
	"net/http"
	"os"
	"os/signal"
	"path"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"syscall"
	"time"
)

const (
	healthPath    = "/healthz"
	gzipMinLength = 256
)

type configField struct {
	Key string
	Env string
	Raw bool // value is inserted as raw JSON (numbers, booleans, objects)
}

var cacheableExt = map[string]bool{
	".js": true, ".mjs": true, ".css": true, ".woff": true, ".woff2": true, ".ttf": true, ".eot": true,
	".svg": true, ".png": true, ".jpg": true, ".jpeg": true, ".gif": true, ".ico": true, ".webp": true,
	".avif": true, ".wasm": true,
}

var compressibleExt = map[string]bool{
	".html": true, ".css": true, ".js": true, ".mjs": true, ".json": true, ".txt": true,
	".xml": true, ".svg": true, ".map": true, ".webmanifest": true, ".wasm": true,
}

func init() {
	for ext, typ := range map[string]string{
		".woff": "font/woff", ".woff2": "font/woff2", ".ttf": "font/ttf",
		".eot": "application/vnd.ms-fontobject", ".ico": "image/x-icon",
		".txt": "text/plain; charset=utf-8", ".map": "application/json",
		".mjs": "text/javascript; charset=utf-8", ".webmanifest": "application/manifest+json",
		".wasm": "application/wasm", ".avif": "image/avif",
	} {
		_ = mime.AddExtensionType(ext, typ)
	}
}

type server struct {
	root          string
	gz            map[string][]byte
	runtimeConfig []byte
}

func main() {
	healthcheck := flag.Bool("healthcheck", false, "probe the local server and exit 0 (healthy) or 1")
	flag.Parse()

	port := getenv("PORT", "8080")
	if *healthcheck {
		os.Exit(runHealthcheck(port))
	}

	root := getenv("STATIC_DIR", "/app/www")
	s, err := newServer(root)
	if err != nil {
		log.Fatalf("startup: %v", err)
	}

	srv := &http.Server{
		Addr:              ":" + port,
		Handler:           accessLog(s),
		ReadHeaderTimeout: 10 * time.Second,
		ReadTimeout:       30 * time.Second,
		WriteTimeout:      60 * time.Second,
		IdleTimeout:       65 * time.Second,
	}

	ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer stop()
	go func() {
		log.Printf("listening on :%s, serving %s", port, root)
		if err := srv.ListenAndServe(); err != nil && !errors.Is(err, http.ErrServerClosed) {
			log.Fatalf("listen: %v", err)
		}
	}()
	<-ctx.Done()
	log.Println("shutdown signal received, draining connections")
	shutdownCtx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	if err := srv.Shutdown(shutdownCtx); err != nil {
		log.Printf("shutdown: %v", err)
	}
}

func newServer(root string) (*server, error) {
	if fi, err := os.Stat(filepath.Join(root, "index.html")); err != nil || fi.IsDir() {
		return nil, fmt.Errorf("index.html not found in %s", root)
	}
	s := &server{root: root, gz: map[string][]byte{}}
	if os.Getenv("USE_RUNTIME_CONFIG") == "true" && len(configFields) > 0 {
		cfg, err := renderRuntimeConfig(root)
		if err != nil {
			return nil, err
		}
		s.runtimeConfig = cfg
		log.Printf("%s generated from environment variables", configURLPath)
	} else {
		log.Printf("using build-time %s", configURLPath)
	}
	if err := s.precompress(); err != nil {
		return nil, fmt.Errorf("precompress: %w", err)
	}
	return s, nil
}

// renderRuntimeConfig builds the JSON in configFields order. A field whose env var
// is set takes that value; otherwise the build-time value from the bundled config
// file is kept, so you only need to set the variables you want to change. Keys in
// the build-time file that have no field are carried over unchanged, sorted.
func renderRuntimeConfig(root string) ([]byte, error) {
	base := map[string]json.RawMessage{}
	if data, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(configURLPath))); err == nil {
		if err := json.Unmarshal(data, &base); err != nil {
			log.Printf("warning: build-time %s is not a JSON object (%v); ignoring it", configURLPath, err)
			base = map[string]json.RawMessage{}
		}
	}
	type entry struct {
		key string
		val []byte
	}
	var entries []entry
	seen := map[string]bool{}
	for _, f := range configFields {
		seen[f.Key] = true
		val, set := os.LookupEnv(f.Env)
		var encoded []byte
		switch {
		case !set:
			if b, ok := base[f.Key]; ok {
				encoded = b
			} else {
				log.Printf("warning: %s is not set and %q has no build-time value", f.Env, f.Key)
				if f.Raw {
					encoded = []byte("null")
				} else {
					encoded = []byte("\"\"")
				}
			}
		case f.Raw:
			if strings.TrimSpace(val) == "" {
				encoded = []byte("null")
			} else if !json.Valid([]byte(val)) {
				return nil, fmt.Errorf("%s must be valid JSON for key %q", f.Env, f.Key)
			} else {
				encoded = []byte(strings.TrimSpace(val))
			}
		default:
			encoded, _ = json.Marshal(val)
		}
		entries = append(entries, entry{f.Key, encoded})
	}
	var extra []string
	for k := range base {
		if !seen[k] {
			extra = append(extra, k)
		}
	}
	sort.Strings(extra)
	for _, k := range extra {
		entries = append(entries, entry{k, base[k]})
	}

	var b bytes.Buffer
	b.WriteString("{\n")
	for i, e := range entries {
		var compact bytes.Buffer
		if err := json.Compact(&compact, e.val); err != nil {
			return nil, fmt.Errorf("value for %q: %w", e.key, err)
		}
		key, _ := json.Marshal(e.key)
		fmt.Fprintf(&b, "  %s: %s", key, compact.Bytes())
		if i < len(entries)-1 {
			b.WriteString(",")
		}
		b.WriteString("\n")
	}
	b.WriteString("}\n")
	return b.Bytes(), nil
}

func (s *server) precompress() error {
	count := 0
	err := filepath.WalkDir(s.root, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() || !compressibleExt[strings.ToLower(filepath.Ext(p))] {
			return nil
		}
		data, err := os.ReadFile(p)
		if err != nil {
			return err
		}
		if len(data) < gzipMinLength {
			return nil
		}
		var buf bytes.Buffer
		zw, _ := gzip.NewWriterLevel(&buf, gzip.BestCompression)
		if _, err := zw.Write(data); err != nil {
			return err
		}
		if err := zw.Close(); err != nil {
			return err
		}
		if buf.Len() >= len(data) {
			return nil
		}
		rel, err := filepath.Rel(s.root, p)
		if err != nil {
			return err
		}
		s.gz["/"+filepath.ToSlash(rel)] = buf.Bytes()
		count++
		return nil
	})
	log.Printf("pre-compressed %d assets", count)
	return err
}

func (s *server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	h := w.Header()
	for _, kv := range securityHeaders {
		h.Set(kv[0], kv[1])
	}
	if r.Method != http.MethodGet && r.Method != http.MethodHead {
		h.Set("Allow", "GET, HEAD")
		http.Error(w, http.StatusText(http.StatusMethodNotAllowed), http.StatusMethodNotAllowed)
		return
	}
	p := path.Clean("/" + r.URL.Path)

	if p == healthPath {
		h.Set("Cache-Control", "no-store")
		h.Set("Content-Type", "text/plain; charset=utf-8")
		_, _ = w.Write([]byte("ok\n"))
		return
	}
	if p == configURLPath && s.runtimeConfig != nil {
		h.Set("Cache-Control", "no-cache, no-store, must-revalidate")
		h.Set("Content-Type", "application/json")
		h.Set("Content-Length", strconv.Itoa(len(s.runtimeConfig)))
		_, _ = w.Write(s.runtimeConfig)
		return
	}
	if cacheableExt[strings.ToLower(path.Ext(p))] {
		if !s.isRegularFile(p) {
			http.NotFound(w, r)
			return
		}
		h.Set("Cache-Control", "public, max-age=31536000, immutable")
		s.serveFile(w, r, p)
		return
	}
	h.Set("Cache-Control", "no-cache, no-store, must-revalidate")
	target := p
	if !s.isRegularFile(target) {
		if idx := path.Join(target, "index.html"); s.isRegularFile(idx) {
			target = idx
		} else {
			target = "/index.html"
		}
	}
	s.serveFile(w, r, target)
}

func (s *server) fsPath(urlPath string) string {
	return filepath.Join(s.root, filepath.FromSlash(urlPath))
}

func (s *server) isRegularFile(urlPath string) bool {
	fi, err := os.Stat(s.fsPath(urlPath))
	return err == nil && fi.Mode().IsRegular()
}

func (s *server) serveFile(w http.ResponseWriter, r *http.Request, urlPath string) {
	f, err := os.Open(s.fsPath(urlPath))
	if err != nil {
		http.NotFound(w, r)
		return
	}
	defer f.Close()
	fi, err := f.Stat()
	if err != nil || !fi.Mode().IsRegular() {
		http.NotFound(w, r)
		return
	}
	ext := strings.ToLower(path.Ext(urlPath))
	ctype := mime.TypeByExtension(ext)
	if ctype == "" {
		ctype = "application/octet-stream"
	}
	h := w.Header()
	h.Set("Content-Type", ctype)
	if compressibleExt[ext] {
		h.Add("Vary", "Accept-Encoding")
	}
	if gz, ok := s.gz[urlPath]; ok && acceptsGzip(r) {
		h.Set("Content-Encoding", "gzip")
		r.Header.Del("Range")
		http.ServeContent(w, r, "", fi.ModTime(), bytes.NewReader(gz))
		return
	}
	http.ServeContent(w, r, "", fi.ModTime(), f)
}

func acceptsGzip(r *http.Request) bool {
	for _, part := range strings.Split(r.Header.Get("Accept-Encoding"), ",") {
		enc, params, _ := strings.Cut(strings.TrimSpace(part), ";")
		if !strings.EqualFold(strings.TrimSpace(enc), "gzip") {
			continue
		}
		if q, ok := strings.CutPrefix(strings.TrimSpace(params), "q="); ok {
			if v, err := strconv.ParseFloat(q, 64); err == nil && v == 0 {
				return false
			}
		}
		return true
	}
	return false
}

type statusRecorder struct {
	http.ResponseWriter
	status int
	bytes  int
}

func (r *statusRecorder) WriteHeader(code int) {
	r.status = code
	r.ResponseWriter.WriteHeader(code)
}

func (r *statusRecorder) Write(b []byte) (int, error) {
	if r.status == 0 {
		r.status = http.StatusOK
	}
	n, err := r.ResponseWriter.Write(b)
	r.bytes += n
	return n, err
}

func accessLog(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		p := r.URL.Path
		if p == healthPath || cacheableExt[strings.ToLower(path.Ext(p))] {
			next.ServeHTTP(w, r)
			return
		}
		start := time.Now()
		rec := &statusRecorder{ResponseWriter: w}
		next.ServeHTTP(rec, r)
		if rec.status == 0 {
			rec.status = http.StatusOK
		}
		log.Printf("%s %s %s %d %dB %s %q", r.RemoteAddr, r.Method, r.URL.RequestURI(),
			rec.status, rec.bytes, time.Since(start).Round(time.Microsecond), r.UserAgent())
	})
}

func runHealthcheck(port string) int {
	client := http.Client{Timeout: 3 * time.Second}
	resp, err := client.Get("http://127.0.0.1:" + port + healthPath)
	if err != nil {
		fmt.Fprintln(os.Stderr, "unhealthy:", err)
		return 1
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		fmt.Fprintln(os.Stderr, "unhealthy: status", resp.StatusCode)
		return 1
	}
	return 0
}

func getenv(key, def string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return def
}
`;

export const GO_MOD = "module distroless-spa-server\n\ngo 1.24\n";
