/* Stack contract, the markdown migration report and the closing console summary. */
import { Plan, rel } from "./files";
import { Prompter } from "./prompt";
import { Block, G, panel, s } from "./ui";

export const TOOL = "distroless-setup";
export const VERSION = "0.3.0";
export const MARKER = `Generated by ${TOOL}`;
export const REPORT_NAME = "DISTROLESS-MIGRATION.md";

export interface Ctx {
  repo: string;
  P: Prompter;
  plan: Plan;
  dryRun: boolean;
}

export interface ActionItem {
  short: string; // console line
  md: string; // report paragraph
}

export interface StackResult {
  stack: string; // "Angular", "Node.js (NestJS)", ...
  imageName: string; // local image tag base
  port: string;
  runtimeImage: string;
  summary: string[]; // key facts for the report summary table: "label: value"
  consoleFacts: string[]; // lines for the console summary
  actions: ActionItem[]; // stack-specific, most important first
  sections: string[]; // markdown sections (each starts with "## ")
  runEnv: string[]; // "-e X=..." examples for docker run
  verify: string[]; // extra verify commands
  dockerignoreRecommended: string[];
  dockerignoreNeeded: string[];
  reviewHits?: string[];
  healthPath: string | null;
  /** Paths that must stay writable under a read-only root filesystem ([] = none). */
  writablePaths: string[];
}

export interface Stack {
  id: "angular" | "node" | "python" | "react";
  title: string;
  /** Confidence 0..1 that the repo is this kind of app, plus a one-line reason. */
  detect(repo: string): { score: number; reason: string } | null;
  run(ctx: Ctx): Promise<StackResult>;
}

export const mdCode = (v: string) => (v.includes("`") ? `\`\` ${v} \`\`` : `\`${v}\``);
const cell = (v: string) => String(v).replace(/\|/g, "\\|").replace(/\n/g, " ");
export function mdTable(headers: string[], rows: string[][]): string {
  return [
    "| " + headers.join(" | ") + " |",
    "|" + headers.map(() => "---").join("|") + "|",
    ...rows.map((r) => "| " + r.map(cell).join(" | ") + " |"),
  ].join("\n");
}

export function commonActions(r: StackResult, hits: string[]): ActionItem[] {
  const items: ActionItem[] = [];
  if (!r.runtimeImage.includes("@sha256:"))
    items.push({
      short: "Pin the runtime image by digest in CI",
      md: `Pin the runtime image by digest for reproducible, scan-stable builds. Get it with \`docker buildx imagetools inspect ${r.runtimeImage}\` and automate updates with Renovate or Dependabot.`,
    });
  items.push({
    short: `Kubernetes/OpenShift: httpGet probes on ${r.healthPath ?? "a health endpoint"}`,
    md: `Kubernetes and OpenShift ignore the Dockerfile \`HEALTHCHECK\`. Add liveness/readiness \`httpGet\` probes on ${r.healthPath ? `\`${r.healthPath}\`` : "a health endpoint"}, port ${r.port}, and the security context under [Deploying](#deploying).`,
  });
  if (hits.length)
    items.push({
      short: `Review ${hits.length} reference(s) to nginx/shell tools in CI and scripts`,
      md: `Review ${hits.length} reference(s) to nginx or shell tools in CI files and scripts; distroless images have no shell. See [Other references to review](#other-references-to-review).`,
    });
  items.push({ short: "Build, run and verify locally (commands in the report)", md: "Build, run and verify locally with the commands under [Build, run, verify](#build-run-verify)." });
  return items;
}

export function renderReport(ctx: Ctx, r: StackResult, hits: string[]): string {
  const { plan, repo } = ctx;
  const now = new Date().toISOString().slice(0, 16).replace("T", " ");
  const L: string[] = ["# Distroless migration report", "", `> ${MARKER} v${VERSION} on ${now} (${r.stack}).`, ""];
  if (ctx.dryRun) L.push("> **DRY RUN.** Nothing in the repo was changed. This report shows what the run *would* do.", "");

  const counts = plan.counts();
  const files = Object.entries(counts).map(([k, v]) => `${v} ${k === "REMOVE" ? "removed" : k.toLowerCase() + "d"}`).join(", ");
  L.push("## Summary", "", mdTable(["", ""], [
    ["Stack", r.stack], ["Runtime image", `\`${r.runtimeImage}\``], ["Port", r.port],
    ...r.summary.map((x) => { const i = x.indexOf(": "); return [x.slice(0, i), x.slice(i + 2)]; }),
    ["Files", files || "none"],
  ]), "");

  const items = [...r.actions, ...commonActions(r, hits)];
  L.push("## Action required", "", "Work through these in order:", "", ...items.map((it, i) => `${i + 1}. ${it.md}`), "");

  L.push("## Files", "", mdTable(["Action", "File", "Why"], plan.actions.map((a) => [plan.label(a), `\`${rel(repo, a.path)}\``, a.reason])), "");
  if (plan.willBackup())
    L.push(`Every updated or removed file ${ctx.dryRun ? "will be" : "was"} copied to \`${rel(repo, plan.backupRoot)}/\` first. To undo, copy those files back and delete the created ones.`, "");

  for (const sec of r.sections) L.push(sec.trimEnd(), "");

  const tag = `${r.imageName}:distroless`;
  const run = [`docker run --rm -p ${r.port}:${r.port}`, ...r.runEnv.map((e) => `  ${e}`), `  ${tag}`].join(" \\\n");
  const tmpfs = r.writablePaths.map((p) => `--tmpfs ${p} `).join("");
  L.push("## Build, run, verify", "", "```bash", `docker build -t ${tag} .`, run, "",
    ...(r.healthPath ? [`curl -si http://localhost:${r.port}${r.healthPath}`] : []), ...r.verify,
    `docker run --rm --entrypoint sh ${tag}   # fails: there is no shell, as intended`,
    `docker inspect --format '{{.State.Health.Status}}' <container-id>`, "",
    `# Same check the platform applies with readOnlyRootFilesystem: true`,
    `docker run --rm --read-only ${tmpfs}-p ${r.port}:${r.port} ${tag}`, "```", "",
    r.writablePaths.length
      ? `The image writes nothing outside ${r.writablePaths.map((p) => `\`${p}\``).join(", ")}. Under \`readOnlyRootFilesystem: true\`, mount an \`emptyDir\` at ${r.writablePaths.length > 1 ? "each of those paths" : `\`${r.writablePaths[0]}\``}.`
      : "The image writes nothing to disk at runtime, so `readOnlyRootFilesystem: true` needs no volumes at all.", "");

  L.push("## Deploying", "",
    "Kubernetes (OpenShift: the same, but leave out `runAsUser` and let the platform assign the UID):", "", "```yaml",
    "securityContext:", "  runAsNonRoot: true", "  readOnlyRootFilesystem: true", "  allowPrivilegeEscalation: false",
    "  capabilities: { drop: [\"ALL\"] }", "  seccompProfile: { type: RuntimeDefault }",
    ...(r.healthPath ? [
      "livenessProbe:", `  httpGet: { path: ${r.healthPath}, port: ${r.port} }`, "  initialDelaySeconds: 5", "  periodSeconds: 30",
      "readinessProbe:", `  httpGet: { path: ${r.healthPath}, port: ${r.port} }`, "  periodSeconds: 10",
    ] : []), "```", "",
    "Debugging without a shell: use `kubectl debug -it <pod> --image=busybox --target=<container>`, or temporarily switch the runtime `FROM` to the `:debug-nonroot` tag locally (never ship it).", "");

  if (hits.length) L.push("## Other references to review", "", ...hits.map((h) => `- \`${h}\``), "");
  return L.join("\n").replace(/\n{3,}/g, "\n\n") + "\n";
}

export function printSummary(ctx: Ctx, r: StackResult, hits: string[], backup: string | null, reportRel: string) {
  const { plan } = ctx;
  const col = { CREATE: "green", UPDATE: "yellow", REMOVE: "red" } as const;
  const changes = [Object.entries(plan.counts()).map(([k, v]) => s(`${v} ${k.toLowerCase()}`, col[k as keyof typeof col], "bold")).join("   ") || "no changes"];
  if (backup) changes.push(`${s("backups", "gray")}  ${rel(ctx.repo, backup)}/`);
  const items = [...r.actions, ...commonActions(r, hits)];
  const blocks: Block[] = [
    ["Changes" + (ctx.dryRun ? " (dry run, nothing written)" : ""), changes],
    [r.stack, r.consoleFacts],
    [s(`Action required (${items.length})`, "yellow"), items.map((it, i) => `${s(i + 1 + ".", "yellow", "bold")} ${it.short}`)],
    ["Next", [
      `${s("$", "gray")} docker build -t ${r.imageName}:distroless .`,
      `${s("$", "gray")} docker run --rm -p ${r.port}:${r.port} ${r.imageName}:distroless`,
      "",
      `${s(G.arrow, "cyan")} Full details: ${s(reportRel, "cyan", "bold")}`,
    ]],
  ];
  process.stdout.write("\n");
  panel(`${G.diamond} ${TOOL}: ${ctx.dryRun ? "dry run complete" : "done"}`, blocks, ctx.dryRun ? "yellow" : "green");
}
